# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: '12.x`
      - name: Setup Project
        run: yarn
      - name: Test Random Pudim
        run: yarn workspace @dojojo/random-pudim run test --watchAll=false
      - name: Test Game Searcher
        run: yarn workspace @dojojo/game-searcher run test --watchAll=false
